# -*- coding: utf-8 -*-
"""
/***************************************************************************
 geocubeviewer
                                 A QGIS plugin
 Geocube XYZ Viewer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-18
        copyright            : (C) 2022 by Guillaume COLLOT
        email                : guillaume.collot@airbus.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load geocubeviewer class from file geocubeviewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geocubeviewer import GeocubeViewer
    return GeocubeViewer(iface)
